# Generated by Django 5.0.3 on 2024-03-13 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
